project_name: kustomize-helmgenerator

env:
  - GO111MODULE=on

env_files:
  gitlab_token: .gitlab_token

gitlab_urls:
  api: "https://repo1.dso.mil/api/v4"
  download: "https://repo1.dso.mil"

before:
  hooks:
    - go mod tidy

builds:
  - binary: HelmChart
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64

archives:
  - format: binary

release:
  gitlab:
    name: "11843"
  name_template: "Version {{.Version}}"
